name = "peerjs-server"
main = "src/index.ts"
compatibility_date = "2025-11-16"

[[durable_objects.bindings]]
name = "PEER_SERVER"
class_name = "PeerServerDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PeerServerDO"]
